name: Create Repository
on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: "Name of the repository to be created"
        required: true
        default: ""

jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Creating Organization Repository
    steps:
      - name: Creating Github Organization Repository
        uses: f1lander/create-repository-action@v1
        with:
          name: "${{ github.event.inputs.repo-name }}"
          access-token: "${{ github.ORG_ADMIN_TOKEN }}"
      - name: Log URL to the repo
        run: echo "The new repo is ${{ steps.create-repo.outputs.repo-url }}"
