name: issue-alarm
on:
  issues:
    types: [opened]

jobs:
  critical-issues:
    runs-on: ubuntu-latest
    if: startswith('${{ github.event.issue.title }}', 'critical')
    steps:
      - name: critical notify
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: critical-issue
          payload: |
            {
              "text": "CRITICAL_ISSUE_UPLOADED",
              "attachments": [
                {
                  "pretext": "critical issue",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "ciritical issue is uploaded",
                      "short": true,
                      "value": "${{ github.event.issue.title }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.CRITICAL_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  normal-issues:
    runs-on: ubuntu-latest
    if: startswith('${{ github.event.issue.title }}', 'normal')
    steps:
      - name: normal notify
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: normal-issue
          payload: |
            {
              "text": "NORMAL_ISSUE_UPLOADED",
              "attachments": [
                {
                  "pretext": "normal issue",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "normal issue is uploaded",
                      "short": true,
                      "value": "${{ github.event.issue.title }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.NORMAL_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
